"""add users.session_epoch for session invalidation on password reset

Revision ID: 8c201dddb7dc
Revises: c7ae5ec98d9e
Create Date: 2026-09-09 22:52:37.304385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c201dddb7dc'
down_revision: Union[str, None] = 'c7ae5ec98d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_epoch', sa.Integer(),
                                nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_epoch')

    # ### end Alembic commands ###
