"""Alembic environment: async engine for aiosqlite (lite) and asyncpg
(standard+). The database URL always comes from app settings
(IDP_DATABASE_URL env → app.config) — `sqlalchemy.url` in alembic.ini is a
placeholder, so the CLI and the app runtime share one source of truth.

`render_as_batch=True` makes ALTER TABLE possible on SQLite (batch mode);
`compare_type=True` keeps autogenerated revisions honest about column types.
"""
import asyncio

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context
from app import integrations  # noqa: F401
from app import models  # noqa: F401  register tables on the metadata
import app.integrations.webhooks  # noqa: F401  webhooks table lives here, not in models.py
from app.config import get_settings
from app.db import Base

config = context.config

_configured_url = (config.get_main_option("sqlalchemy.url") or "").strip()
if not _configured_url:
    config.set_main_option("sqlalchemy.url",
                           get_settings().database_url.replace("%", "%%"))

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _run_sync(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def _run_async() -> None:
    engine = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with engine.connect() as connection:
        await connection.run_sync(_run_sync)
    await engine.dispose()


def run_migrations_online() -> None:
    # Safe both from the CLI and from `asyncio.to_thread` inside the app
    # lifespan: this coroutine runs in a thread with no event loop of its own.
    asyncio.run(_run_async())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
